#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
  default:
         - step:
              name: Build and Test
              caches:
                  - dotnetcore
              script:
                  - dotnet restore
                  - dotnet build
                  - dotnet test
  branches:
        master:
            - step:
                  name: "Package"
                  caches:
                      - dotnetcore
                  script:
                      - cd management-dddnetcore
                      - apt-get update
                      - apt-get install zip -y
                      # Build all
                      - dotnet build
                      # Web
                      - dotnet publish -c Release -o ./publish
                      - cd ./publish
                  
            - step:
                  name: Deploy
                  deployment: Production
                  trigger: manual
                  
                  script:
                      - pwd
                      - ls

   
